version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    container_name: next-auth-frontend
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - API_BASE_URL=${API_BASE_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_DISABLE_ESLINT=true
      - NEXT_DISABLE_TYPECHECK=true
    networks:
      - frontend-network
      - Nelinen-network-production

networks:
  frontend-network:
    driver: bridge
  Nelinen-network-production:
    external: true 