version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-auth-frontend-dev
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3005
      - NEXTAUTH_SECRET=your-super-secret-nextauth-key-change-this-in-production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
      - API_BASE_URL=http://auth-nest-app:3000
      - NEXT_DISABLE_ESLINT=true
      - NEXT_DISABLE_TYPECHECK=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network
      - auth-nest-js_auth-network

networks:
  frontend-network:
    driver: bridge
  auth-nest-js_auth-network:
    external: true 