version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: next-auth-frontend-dev
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - API_BASE_URL=${API_BASE_URL_DEV}
      - NEXT_DISABLE_ESLINT=true
      - NEXT_DISABLE_TYPECHECK=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - frontend-network
      - auth-nest-js_auth-network-dev

networks:
  frontend-network:
    driver: bridge
  auth-nest-js_auth-network-dev:
    external: true 