version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://10.11.9.43:3000
    container_name: next-auth-frontend
    restart: unless-stopped
    ports:
      - "3005:3005"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3005
      - NEXTAUTH_SECRET=your-super-secret-nextauth-key-change-this-in-production
      - API_BASE_URL=http://auth-nest-app:3000
      - NEXT_DISABLE_ESLINT=true
      - NEXT_DISABLE_TYPECHECK=true
    networks:
      - frontend-network
      - auth-nest-js_auth-network

networks:
  frontend-network:
    driver: bridge
  auth-nest-js_auth-network:
    external: true 